export const languages = {
  en: "English",
  ru: "Русский",
  de: "Deutsch",
  zh: "中文",
} as const;

export type Language = keyof typeof languages;

export const languageFlags: Record<Language, string> = {
  en: "gb",
  ru: "ru",
  de: "de",
  zh: "cn",
};

export const translations: Record<Language, Record<string, string>> = {
  en: {
    "navbar.tagline": "Be the best you can be",
    "navbar.hire": "Hire Me",
    "about.title": "About Me",
    "about.subtitle": "A bit about who I am",
    "about.bio":
      "I'm a multi-disciplinary Software Engineer and DevOps Specialist with a proven track record of building robust systems from the ground up. Over the past several years, I've taken on roles ranging from backend developer to technical manager, co-founder, and CTO, leading both product development and infrastructure design across startups and large organizations. At OpenHubble, as Founder and CEO, I oversee everything from code to cloud—combining full-stack engineering with DevOps, security, and team leadership. I bring a product-driven mindset, a deep technical toolkit, and the ability to guide engineering teams toward scalable, secure, and maintainable solutions.",
    "experiences.title": "Experiences",
    "experiences.subtitle": "My professional journey",
    "skills.title": "Skills",
    "skills.subtitle": "Technologies I work with",
    "message.title": "Send a Message",
    "message.subtitle": "Get in touch!",
    "message.description": "Contact me directly by sending a message below.",
    "message.form.name": "Name",
    "message.form.email": "Email",
    "message.form.message": "Message",
    "message.form.send": "Send Message",
    "message.form.sending": "Sending...",
    "message.validation.nameRequired": "Name is required",
    "message.validation.emailRequired": "Email is required",
    "message.validation.emailInvalid": "Email is invalid",
    "message.validation.messageRequired": "Message is required",
    "message.success": "Message sent successfully!",
    "message.error": "Failed to send message",
    "social.title": "Social Media",
    "social.subtitle": "Connect with me online",
    "resume.title": "Download Resume",
    "resume.subtitle": "Grab my resume in PDF",
  },
  ru: {
    "navbar.tagline": "Будьте лучшей версией себя",
    "navbar.hire": "Нанять меня",
    "about.title": "Обо мне",
    "about.subtitle": "Немного о том, кто я",
    "about.bio":
      "Я многопрофильный инженер-программист и специалист по DevOps с доказанным опытом создания надежных систем с нуля. За последние несколько лет я занимал должности от backend-разработчика до технического менеджера, соучредителя и CTO, руководя разработкой продуктов и проектированием инфраструктуры в стартапах и крупных организациях. В OpenHubble, как основатель и генеральный директор, я контролирую все, от кода до облака, комбинируя полнофункциональную инженерию с DevOps, безопасностью и лидерством команды. Я привношу менталитет, ориентированный на продукт, глубокий технический арсенал и способность направлять инженерные команды к масштабируемым, безопасным и поддерживаемым решениям.",
    "experiences.title": "Опыт",
    "experiences.subtitle": "Мой профессиональный путь",
    "skills.title": "Навыки",
    "skills.subtitle": "Технологии, с которыми я работаю",
    "message.title": "Отправить сообщение",
    "message.subtitle": "Свяжитесь со мной!",
    "message.description":
      "Свяжитесь со мной напрямую, отправив сообщение ниже.",
    "message.form.name": "Имя",
    "message.form.email": "Электронная почта",
    "message.form.message": "Сообщение",
    "message.form.send": "Отправить сообщение",
    "message.form.sending": "Отправка...",
    "message.validation.nameRequired": "Имя обязательно",
    "message.validation.emailRequired": "Электронная почта обязательна",
    "message.validation.emailInvalid": "Адрес электронной почты неверный",
    "message.validation.messageRequired": "Сообщение обязательно",
    "message.success": "Сообщение успешно отправлено!",
    "message.error": "Ошибка при отправке сообщения",
    "social.title": "Социальные сети",
    "social.subtitle": "Свяжитесь со мной в интернете",
    "resume.title": "Скачать резюме",
    "resume.subtitle": "Получите мое резюме в PDF",
  },
  de: {
    "navbar.tagline": "Seien Sie die beste Version Ihrer selbst",
    "navbar.hire": "Stellen Sie mich ein",
    "about.title": "Über mich",
    "about.subtitle": "Ein wenig über mich",
    "about.bio":
      "Ich bin ein vielseitiger Software-Ingenieur und DevOps-Spezialist mit einer nachgewiesenen Erfolgsbilanz beim Aufbau robuster Systeme von Grund auf. In den letzten Jahren habe ich verschiedene Rollen vom Backend-Entwickler bis zum technischen Manager, Mitgründer und CTO übernommen und sowohl die Produktentwicklung als auch das Infrastruktur-Design in Startups und großen Organisationen geleitet. Bei OpenHubble beaufsichtige ich als Gründer und CEO alles vom Code bis zur Cloud und kombiniere vollständige Software-Engineering mit DevOps, Sicherheit und Teamleitung. Ich bringe eine produktgetriebene Denkweise, ein tiefes technisches Toolkit und die Fähigkeit mit, Engineering-Teams zu skalierbaren, sicheren und wartbaren Lösungen zu führen.",
    "experiences.title": "Erfahrungen",
    "experiences.subtitle": "Meine berufliche Reise",
    "skills.title": "Fähigkeiten",
    "skills.subtitle": "Technologien, mit denen ich arbeite",
    "message.title": "Nachricht senden",
    "message.subtitle": "Kontaktieren Sie mich!",
    "message.description":
      "Kontaktieren Sie mich direkt, indem Sie unten eine Nachricht senden.",
    "message.form.name": "Name",
    "message.form.email": "E-Mail",
    "message.form.message": "Nachricht",
    "message.form.send": "Nachricht senden",
    "message.form.sending": "Wird gesendet...",
    "message.validation.nameRequired": "Name ist erforderlich",
    "message.validation.emailRequired": "E-Mail ist erforderlich",
    "message.validation.emailInvalid": "E-Mail ist ungültig",
    "message.validation.messageRequired": "Nachricht ist erforderlich",
    "message.success": "Nachricht erfolgreich versendet!",
    "message.error": "Fehler beim Senden der Nachricht",
    "social.title": "Soziale Medien",
    "social.subtitle": "Verbinde dich mit mir online",
    "resume.title": "Lebenslauf herunterladen",
    "resume.subtitle": "Holen Sie sich meinen Lebenslauf als PDF",
  },
  zh: {
    "navbar.tagline": "做最好的自己",
    "navbar.hire": "聘请我",
    "about.title": "关于我",
    "about.subtitle": "一点关于我是谁",
    "about.bio":
      "我是一名多学科的软件工程师和DevOps专家，在从零开始构建强大系统方面有着卓越的记录。在过去的几年里，我从事从后端开发人员到技术经理、联合创始人和首席技术官的各种角色，领导初创公司和大型组织的产品开发和基础设施设计。作为OpenHubble的创始人兼首席执行官，我监督从代码到云的一切——结合全栈工程、DevOps、安全和团队领导。我带来了以产品为驱动的心态、深厚的技术工具包以及指导工程团队实现可扩展、安全和可维护解决方案的能力。",
    "experiences.title": "经验",
    "experiences.subtitle": "我的职业历程",
    "skills.title": "技能",
    "skills.subtitle": "我使用的技术",
    "message.title": "发送消息",
    "message.subtitle": "联系我！",
    "message.description": "请在下方发送消息直接与我联系。",
    "message.form.name": "姓名",
    "message.form.email": "电子邮件",
    "message.form.message": "消息",
    "message.form.send": "发送消息",
    "message.form.sending": "正在发送...",
    "message.validation.nameRequired": "需要姓名",
    "message.validation.emailRequired": "需要电子邮件",
    "message.validation.emailInvalid": "电子邮件无效",
    "message.validation.messageRequired": "需要消息",
    "message.success": "消息发送成功！",
    "message.error": "发送消息失败",
    "social.title": "社交媒体",
    "social.subtitle": "在线与我联系",
    "resume.title": "下载简历",
    "resume.subtitle": "获取我的 PDF 简历",
  },
};
