server {
	listen 80;
	listen [::]:80;
	
	server_name amirhossein.info;

	location / {
		return 301 https://$host$request_uri;
	}
}

server {
	listen 443 ssl;
	listen [::]:443 ssl;

	server_name amirhossein.info;

	ssl_certificate /etc/nginx/ssl/amirhossein.info/fullchain.pem;
	ssl_certificate_key /etc/nginx/ssl/amirhossein.info/privkey.pem;

	gzip on;
	gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
	gzip_vary on;
	gzip_min_length 1000;

	# location / {
		# proxy_pass http://resume-frontend:3000;
		# proxy_http_version 1.1;
		# proxy_set_header Upgrade $http_upgrade;
		# proxy_set_header Connection "Upgrade";
		# proxy_set_header Host $host;
	# }

	location /api/ {
		proxy_pass http://resume-backend:8000;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "Upgrade";
		proxy_set_header Host $host;
	}
}
